In [11]:
import pandas as pd
df = pd.read_csv("../dataset/archive/football_players_value_dataset.csv")
df

,name,Age,Overall rating,Potential,Team & Contract,ID,Height,Weight,foot,Best overall,...,GK Reflexes,Total stats,Base stats,International reputation,Pace / Diving,Shooting / Handling,Passing / Kicking,Dribbling / Reflexes,Defending / Pace,Unnamed: 64
0,A. Younes LM CAM,29,73,73,Al Ettifaq\n2022 ~ 2024,205966,"170cm / 5'7""",71kg / 157lbs,Right,73,...,15,1842,387,1,71,67,70,79,38,NaN
1,R. Sessegnon LB LWB,23,75,80,Tottenham Hotspur\n2019 ~ 2025,235883,"178cm / 5'10""",70kg / 154lbs,Left,77,...,7,1960,425,1,78,64,72,76,71,NaN
2,Mikel Merino CM CAM,27,84,85,Real Sociedad\n2018 ~ 2025,225193,"189cm / 6'2""",83kg / 183lbs,Left,85,...,14,2282,480,2,72,79,82,82,83,NaN
3,M. Prati CDM CM,19,73,85,Cagliari\n2023 ~ 2028,272725,"185cm / 6'1""",75kg / 165lbs,Right,75,...,9,1977,414,1,65,65,73,72,69,NaN
4,L. Rodríguez RW LW ST,19,71,83,Liverpool\n2023 ~ 2027,273604,"179cm / 5'10""",71kg / 157lbs,Right,72,...,15,1879,400,1,83,74,58,77,37,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3055,Ontiveros LM RM ST,25,69,70,Villarreal II\n2022 ~ 2024,231640,"172cm / 5'8""",75kg / 165lbs,Right,69,...,12,1682,354,1,59,69,73,69,35,NaN
3056,A. Ömür CM CAM RM,24,72,76,Hull City\n2024 ~ 2027,231777,"168cm / 5'6""",70kg / 154lbs,Left,77,...,10,1954,408,1,82,67,72,80,53,NaN
3057,Álvaro Tejero RB RWB,26,72,73,SD Eibar\n2019 ~ 2024,231856,"174cm / 5'9""",69kg / 152lbs,Right,72,...,7,1972,419,1,81,64,69,71,65,NaN
3058,Y. Dhanda CAM,24,68,72,Ross County\n2022 ~ 2024,231863,"171cm / 5'7""",63kg / 139lbs,Right,70,...,8,1718,367,1,72,61,66,72,42,NaN
3059,M. van Bergen RM LM,23,70+1,73+1,FC Twente\n2023 ~ 2027,231864,"170cm / 5'7""",62kg / 137lbs,Right,71,...,11,1706,366,1,88,63,64,71,27,NaN

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3060 entries, 0 to 3059
Data columns (total 65 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   name                      3060 non-null   object
 1   Age                       3060 non-null   int64
 2   Overall rating            3060 non-null   object
 3   Potential                 3060 non-null   object
 4   Team & Contract           3060 non-null   object
 5   ID                        3060 non-null   int64
 6   Height                    3060 non-null   object
 7   Weight                    3060 non-null   object
 8   foot                      3060 non-null   object
 9   Best overall              3060 non-null   int64
 10  Best position             3060 non-null   object
 11  Growth                    3060 non-null   int64
 12  Value                     3060 non-null   object
 13  Wage                      3060 non-null   object
 14  Release clause            3060 non-null   object
 15  Total attacking           3060 non-null   int64
 16  Crossing                  3060 non-null   object
 17  Finishing                 3060 non-null   object
 18  Heading accuracy          3060 non-null   object
 19  Short passing             3060 non-null   object
 20  Volleys                   3060 non-null   object
 21  Total skill               3060 non-null   int64
 22  Dribbling                 3060 non-null   object
 23  Curve                     3060 non-null   object
 24  FK Accuracy               3060 non-null   object
 25  Long passing              3060 non-null   object
 26  Ball control              3060 non-null   object
 27  Total movement            3060 non-null   int64
 28  Acceleration              3060 non-null   object
 29  Sprint speed              3060 non-null   object
 30  Agility                   3060 non-null   object
 31  Reactions                 3060 non-null   object
 32  Balance                   3060 non-null   object
 33  Total power               3060 non-null   int64
 34  Shot power                3060 non-null   object
 35  Jumping                   3060 non-null   object
 36  Stamina                   3060 non-null   object
 37  Strength                  3060 non-null   object
 38  Long shots                3060 non-null   object
 39  Total mentality           3060 non-null   int64
 40  Aggression                3060 non-null   object
 41  Interceptions             3060 non-null   object
 42  Att. Position             3060 non-null   object
 43  Vision                    3060 non-null   object
 44  Penalties                 3060 non-null   object
 45  Composure                 3060 non-null   object
 46  Total defending           3060 non-null   int64
 47  Defensive awareness       3060 non-null   object
 48  Standing tackle           3060 non-null   object
 49  Sliding tackle            3060 non-null   object
 50  Total goalkeeping         3060 non-null   int64
 51  GK Diving                 3060 non-null   object
 52  GK Handling               3060 non-null   object
 53  GK Kicking                3060 non-null   object
 54  GK Positioning            3060 non-null   object
 55  GK Reflexes               3060 non-null   object
 56  Total stats               3060 non-null   int64
 57  Base stats                3060 non-null   int64
 58  International reputation  3060 non-null   int64
 59  Pace / Diving             3060 non-null   int64
 60  Shooting / Handling       3060 non-null   int64
 61  Passing / Kicking         3060 non-null   int64
 62  Dribbling / Reflexes      3060 non-null   int64
 63  Defending / Pace          3060 non-null   int64
 64  Unnamed: 64               0 non-null      float64
dtypes: float64(1), int64(19), object(45)
memory usage: 1.5+ MB

In [13]:
df['Value']

0         €3M
1         €8M
2        €48M
3         €7M
4       €4.4M
        ...
3055    €1.7M
3056    €3.3M
3057    €2.5M
3058    €1.7M
3059    €2.2M
Name: Value, Length: 3060, dtype: object

In [14]:
chosen_df = df[['Age',"Overall rating","Shooting / Handling","Dribbling / Reflexes","Defending / Pace","Pace / Diving","Passing / Kicking","Best position","Value"]]
chosen_df

,Age,Overall rating,Shooting / Handling,Dribbling / Reflexes,Defending / Pace,Pace / Diving,Passing / Kicking,Best position,Value
0,29,73,67,79,38,71,70,LM,€3M
1,23,75,64,76,71,78,72,LM,€8M
2,27,84,79,82,83,72,82,CM,€48M
3,19,73,65,72,69,65,73,CM,€7M
4,19,71,74,77,37,83,58,ST,€4.4M
...,...,...,...,...,...,...,...,...,...
3055,25,69,69,69,35,59,73,LM,€1.7M
3056,24,72,67,80,53,82,72,CAM,€3.3M
3057,26,72,64,71,65,81,69,RB,€2.5M
3058,24,68,61,72,42,72,66,CAM,€1.7M
3059,23,70+1,63,71,27,88,64,RM,€2.2M

In [15]:
chosen_df.isnull().sum()

Age                     0
Overall rating          0
Shooting / Handling     0
Dribbling / Reflexes    0
Defending / Pace        0
Pace / Diving           0
Passing / Kicking       0
Best position           0
Value                   0
dtype: int64